<dl><dt> <span class="character_icon" style="white-space: nowrap"><a href="/wiki/Blitzcrank" title="Blitzcrank"><img src="http://img4.wikia.nocookie.net/__cb20091218194413/leagueoflegends/images/thumb/5/5b/BlitzcrankSquare.png/20px-BlitzcrankSquare.png" width="20" height="20" data-image-name="BlitzcrankSquare.png" data-image-key="BlitzcrankSquare.png" data-src="http://img4.wikia.nocookie.net/__cb20091218194413/leagueoflegends/images/thumb/5/5b/BlitzcrankSquare.png/20px-BlitzcrankSquare.png" class="lzyPlcHld lzyTrns lzyLoaded" onload="if(typeof ImgLzy==='object'){ImgLzy.load(this)}"><noscript>&lt;img src="http://img4.wikia.nocookie.net/__cb20091218194413/leagueoflegends/images/thumb/5/5b/BlitzcrankSquare.png/20px-BlitzcrankSquare.png" width="20" height="20" data-image-name="BlitzcrankSquare.png" data-image-key="BlitzcrankSquare.png" /&gt;</noscript></a>&nbsp;<span><a href="/wiki/Blitzcrank" title="Blitzcrank">Blitzcrank</a></span></span>
</dt></dl>
<ul><li> <span style="white-space:nowrap;"><a href="/wiki/Blitzcrank#Rocket_Grab" title="Rocket Grab"><img src="http://img2.wikia.nocookie.net/__cb20130929122703/leagueoflegends/images/thumb/e/e2/Rocket_Grab.png/20px-Rocket_Grab.png" width="20" height="20" data-image-name="Rocket Grab.png" data-image-key="Rocket_Grab.png" data-src="http://img2.wikia.nocookie.net/__cb20130929122703/leagueoflegends/images/thumb/e/e2/Rocket_Grab.png/20px-Rocket_Grab.png" class="lzyPlcHld lzyTrns lzyLoaded" onload="if(typeof ImgLzy==='object'){ImgLzy.load(this)}"><noscript>&lt;img src="http://img2.wikia.nocookie.net/__cb20130929122703/leagueoflegends/images/thumb/e/e2/Rocket_Grab.png/20px-Rocket_Grab.png" width="20" height="20" data-image-name="Rocket Grab.png" data-image-key="Rocket_Grab.png" /&gt;</noscript></a>&nbsp;<a href="/wiki/Blitzcrank#Rocket_Grab" title="Blitzcrank"><span title="Blitzcrank's Rocket Grab">Rocket Grab</span></a></span>
<ul><li> Mana cost reduced to 100 from 120.
</li></ul>
</li><li> <span style="white-space:nowrap;"><a href="/wiki/Blitzcrank#Static_Field" title="Static Field"><img src="http://img4.wikia.nocookie.net/__cb20130929122704/leagueoflegends/images/thumb/a/a6/Static_Field.png/20px-Static_Field.png" width="20" height="20" data-image-name="Static Field.png" data-image-key="Static_Field.png" data-src="http://img4.wikia.nocookie.net/__cb20130929122704/leagueoflegends/images/thumb/a/a6/Static_Field.png/20px-Static_Field.png" class="lzyPlcHld lzyTrns lzyLoaded" onload="if(typeof ImgLzy==='object'){ImgLzy.load(this)}"><noscript>&lt;img src="http://img4.wikia.nocookie.net/__cb20130929122704/leagueoflegends/images/thumb/a/a6/Static_Field.png/20px-Static_Field.png" width="20" height="20" data-image-name="Static Field.png" data-image-key="Static_Field.png" /&gt;</noscript></a>&nbsp;<a href="/wiki/Blitzcrank#Static_Field" title="Blitzcrank"><span title="Blitzcrank's Static Field">Static Field</span></a></span>
<ul><li> Mana cost reduced to 100 from 150.
</li></ul>
</li></ul>
<dl><dt><span class="character_icon" style="white-space: nowrap"><a href="/wiki/Cho%27Gath" title="Cho'Gath"><img src="http://img3.wikia.nocookie.net/__cb20091218194425/leagueoflegends/images/thumb/c/cc/ChoGathSquare.png/20px-ChoGathSquare.png" width="20" height="20" data-image-name="ChoGathSquare.png" data-image-key="ChoGathSquare.png" data-src="http://img3.wikia.nocookie.net/__cb20091218194425/leagueoflegends/images/thumb/c/cc/ChoGathSquare.png/20px-ChoGathSquare.png" class="lzyPlcHld lzyTrns lzyLoaded" onload="if(typeof ImgLzy==='object'){ImgLzy.load(this)}"><noscript>&lt;img src="http://img3.wikia.nocookie.net/__cb20091218194425/leagueoflegends/images/thumb/c/cc/ChoGathSquare.png/20px-ChoGathSquare.png" width="20" height="20" data-image-name="ChoGathSquare.png" data-image-key="ChoGathSquare.png" /&gt;</noscript></a>&nbsp;<span><a href="/wiki/Cho%27Gath" title="Cho'Gath">Cho'Gath</a></span></span>
</dt></dl>
<ul><li> <span style="white-space:nowrap;"><a href="/wiki/Cho%27Gath#Feast" title="Feast"><img src="http://img2.wikia.nocookie.net/__cb20130929122719/leagueoflegends/images/thumb/2/2f/Feast.png/20px-Feast.png" width="20" height="20" data-image-name="Feast.png" data-image-key="Feast.png" data-src="http://img2.wikia.nocookie.net/__cb20130929122719/leagueoflegends/images/thumb/2/2f/Feast.png/20px-Feast.png" class="lzyPlcHld lzyTrns lzyLoaded" onload="if(typeof ImgLzy==='object'){ImgLzy.load(this)}"><noscript>&lt;img src="http://img2.wikia.nocookie.net/__cb20130929122719/leagueoflegends/images/thumb/2/2f/Feast.png/20px-Feast.png" width="20" height="20" data-image-name="Feast.png" data-image-key="Feast.png" /&gt;</noscript></a>&nbsp;<a href="/wiki/Cho%27Gath#Feast" title="Cho'Gath"><span title="Cho'Gath's Feast">Feast</span></a></span>
<ul><li> Cast range increased to 175 from 150.
</li><li> Cast time reduced to 0.25 seconds from 0.5.
</li></ul>
</li></ul>
<dl><dt><span class="character_icon" style="white-space: nowrap"><a href="/wiki/Kha%27Zix" title="Kha'Zix"><img src="http://img3.wikia.nocookie.net/__cb20120921042418/leagueoflegends/images/thumb/b/b5/KhaZixSquare.png/20px-KhaZixSquare.png" width="20" height="20" data-image-name="KhaZixSquare.png" data-image-key="KhaZixSquare.png" data-src="http://img3.wikia.nocookie.net/__cb20120921042418/leagueoflegends/images/thumb/b/b5/KhaZixSquare.png/20px-KhaZixSquare.png" class="lzyPlcHld lzyTrns lzyLoaded" onload="if(typeof ImgLzy==='object'){ImgLzy.load(this)}"><noscript>&lt;img src="http://img3.wikia.nocookie.net/__cb20120921042418/leagueoflegends/images/thumb/b/b5/KhaZixSquare.png/20px-KhaZixSquare.png" width="20" height="20" data-image-name="KhaZixSquare.png" data-image-key="KhaZixSquare.png" /&gt;</noscript></a>&nbsp;<span><a href="/wiki/Kha%27Zix" title="Kha'Zix">Kha'Zix</a></span></span>
</dt></dl>
<ul><li> <span style="white-space:nowrap;"><a href="/wiki/Kha%27Zix#Evolved_Wings" title="Evolved Wings"><img src="http://img2.wikia.nocookie.net/__cb20130929122949/leagueoflegends/images/thumb/5/55/Evolved_Wings.png/20px-Evolved_Wings.png" width="20" height="20" data-image-name="Evolved Wings.png" data-image-key="Evolved_Wings.png" data-src="http://img2.wikia.nocookie.net/__cb20130929122949/leagueoflegends/images/thumb/5/55/Evolved_Wings.png/20px-Evolved_Wings.png" class="lzyPlcHld lzyTrns lzyLoaded" onload="if(typeof ImgLzy==='object'){ImgLzy.load(this)}"><noscript>&lt;img src="http://img2.wikia.nocookie.net/__cb20130929122949/leagueoflegends/images/thumb/5/55/Evolved_Wings.png/20px-Evolved_Wings.png" width="20" height="20" data-image-name="Evolved Wings.png" data-image-key="Evolved_Wings.png" /&gt;</noscript></a>&nbsp;<a href="/wiki/Kha%27Zix#Evolved_Wings" title="Kha'Zix"><span title="Kha'Zix's Evolved Wings">Evolved Wings</span></a></span>
<ul><li> Fixed a bug where Evolved Wings had a longer cooldown than Leap (reduced to 22/20/18/16/14 seconds from 24/22/20/18/16)
</li></ul>
</li></ul>
<dl><dt><span class="character_icon" style="white-space: nowrap"><a href="/wiki/Malzahar" title="Malzahar"><img src="http://img2.wikia.nocookie.net/__cb20120117212750/leagueoflegends/images/thumb/a/a7/MalzaharSquare.png/20px-MalzaharSquare.png" width="20" height="20" data-image-name="MalzaharSquare.png" data-image-key="MalzaharSquare.png" data-src="http://img2.wikia.nocookie.net/__cb20120117212750/leagueoflegends/images/thumb/a/a7/MalzaharSquare.png/20px-MalzaharSquare.png" class="lzyPlcHld lzyTrns lzyLoaded" onload="if(typeof ImgLzy==='object'){ImgLzy.load(this)}"><noscript>&lt;img src="http://img2.wikia.nocookie.net/__cb20120117212750/leagueoflegends/images/thumb/a/a7/MalzaharSquare.png/20px-MalzaharSquare.png" width="20" height="20" data-image-name="MalzaharSquare.png" data-image-key="MalzaharSquare.png" /&gt;</noscript></a>&nbsp;<span><a href="/wiki/Malzahar" title="Malzahar">Malzahar</a></span></span>
</dt></dl>
<ul><li> <span style="white-space:nowrap;"><a href="/wiki/Malzahar#Nether_Grasp" title="Nether Grasp"><img src="http://img2.wikia.nocookie.net/__cb20130929123042/leagueoflegends/images/thumb/4/4e/Nether_Grasp.png/20px-Nether_Grasp.png" width="20" height="20" data-image-name="Nether Grasp.png" data-image-key="Nether_Grasp.png" data-src="http://img2.wikia.nocookie.net/__cb20130929123042/leagueoflegends/images/thumb/4/4e/Nether_Grasp.png/20px-Nether_Grasp.png" class="lzyPlcHld lzyTrns lzyLoaded" onload="if(typeof ImgLzy==='object'){ImgLzy.load(this)}"><noscript>&lt;img src="http://img2.wikia.nocookie.net/__cb20130929123042/leagueoflegends/images/thumb/4/4e/Nether_Grasp.png/20px-Nether_Grasp.png" width="20" height="20" data-image-name="Nether Grasp.png" data-image-key="Nether_Grasp.png" /&gt;</noscript></a>&nbsp;<a href="/wiki/Malzahar#Nether_Grasp" title="Malzahar"><span title="Malzahar's Nether Grasp">Nether Grasp</span></a></span>
<ul><li> Mana cost reduced to 100 from 150.
</li></ul>
</li></ul>
<dl><dt><span class="character_icon" style="white-space: nowrap"><a href="/wiki/Nami" title="Nami"><img src="http://img3.wikia.nocookie.net/__cb20121130222134/leagueoflegends/images/thumb/d/d2/NamiSquare.png/20px-NamiSquare.png" width="20" height="20" data-image-name="NamiSquare.png" data-image-key="NamiSquare.png" data-src="http://img3.wikia.nocookie.net/__cb20121130222134/leagueoflegends/images/thumb/d/d2/NamiSquare.png/20px-NamiSquare.png" class="lzyPlcHld lzyTrns lzyLoaded" onload="if(typeof ImgLzy==='object'){ImgLzy.load(this)}"><noscript>&lt;img src="http://img3.wikia.nocookie.net/__cb20121130222134/leagueoflegends/images/thumb/d/d2/NamiSquare.png/20px-NamiSquare.png" width="20" height="20" data-image-name="NamiSquare.png" data-image-key="NamiSquare.png" /&gt;</noscript></a>&nbsp;<span><a href="/wiki/Nami" title="Nami">Nami</a></span></span>
</dt></dl>
<ul><li> <span style="white-space:nowrap;"><a href="/wiki/Nami#Aqua_Prison" title="Aqua Prison"><img src="http://img4.wikia.nocookie.net/__cb20130929123105/leagueoflegends/images/thumb/c/cb/Aqua_Prison.png/20px-Aqua_Prison.png" width="20" height="20" data-image-name="Aqua Prison.png" data-image-key="Aqua_Prison.png" data-src="http://img4.wikia.nocookie.net/__cb20130929123105/leagueoflegends/images/thumb/c/cb/Aqua_Prison.png/20px-Aqua_Prison.png" class="lzyPlcHld lzyTrns lzyLoaded" onload="if(typeof ImgLzy==='object'){ImgLzy.load(this)}"><noscript>&lt;img src="http://img4.wikia.nocookie.net/__cb20130929123105/leagueoflegends/images/thumb/c/cb/Aqua_Prison.png/20px-Aqua_Prison.png" width="20" height="20" data-image-name="Aqua Prison.png" data-image-key="Aqua_Prison.png" /&gt;</noscript></a>&nbsp;<a href="/wiki/Nami#Aqua_Prison" title="Nami"><span title="Nami's Aqua Prison">Aqua Prison</span></a></span>
<ul><li> Fixed a bug where Aqua Prison could stun targets who were suppose to be immune to crowd control.
</li></ul>
</li></ul>
<dl><dt><span class="character_icon" style="white-space: nowrap"><a href="/wiki/Pantheon" title="Pantheon"><img src="http://img3.wikia.nocookie.net/__cb20130511140006/leagueoflegends/images/thumb/9/9b/PantheonSquare.png/20px-PantheonSquare.png" width="20" height="20" data-image-name="PantheonSquare.png" data-image-key="PantheonSquare.png" data-src="http://img3.wikia.nocookie.net/__cb20130511140006/leagueoflegends/images/thumb/9/9b/PantheonSquare.png/20px-PantheonSquare.png" class="lzyPlcHld lzyTrns lzyLoaded" onload="if(typeof ImgLzy==='object'){ImgLzy.load(this)}"><noscript>&lt;img src="http://img3.wikia.nocookie.net/__cb20130511140006/leagueoflegends/images/thumb/9/9b/PantheonSquare.png/20px-PantheonSquare.png" width="20" height="20" data-image-name="PantheonSquare.png" data-image-key="PantheonSquare.png" /&gt;</noscript></a>&nbsp;<span><a href="/wiki/Pantheon" title="Pantheon">Pantheon</a></span></span>
</dt><dd><i>These changes were implemented last patch, but were missed in the patch notes.</i>
</dd></dl>
<ul><li> <span style="white-space:nowrap;"><a href="/wiki/Pantheon#Grand_Skyfall" title="Grand Skyfall"><img src="http://img4.wikia.nocookie.net/__cb20130929123146/leagueoflegends/images/thumb/d/dd/Grand_Skyfall.png/20px-Grand_Skyfall.png" width="20" height="20" data-image-name="Grand Skyfall.png" data-image-key="Grand_Skyfall.png" data-src="http://img4.wikia.nocookie.net/__cb20130929123146/leagueoflegends/images/thumb/d/dd/Grand_Skyfall.png/20px-Grand_Skyfall.png" class="lzyPlcHld lzyTrns lzyLoaded" onload="if(typeof ImgLzy==='object'){ImgLzy.load(this)}"><noscript>&lt;img src="http://img4.wikia.nocookie.net/__cb20130929123146/leagueoflegends/images/thumb/d/dd/Grand_Skyfall.png/20px-Grand_Skyfall.png" width="20" height="20" data-image-name="Grand Skyfall.png" data-image-key="Grand_Skyfall.png" /&gt;</noscript></a>&nbsp;<a href="/wiki/Pantheon#Grand_Skyfall" title="Pantheon"><span title="Pantheon's Grand Skyfall">Grand Skyfall</span></a></span>
<ul><li> Fixed a bug where Pantheon was able to take damage and cast abilities ~0.5 seconds before he lands - Pantheon will now be untargetable until he lands and will only be able to cast abilities once he's landed.
</li><li> Fixed a bug where Pantheon was hitting the ground 0.5 seconds before the damage was dealt.
</li></ul>
</li></ul>
<dl><dt><span class="character_icon" style="white-space: nowrap"><a href="/wiki/Sejuani" title="Sejuani"><img src="http://img4.wikia.nocookie.net/__cb20130430130347/leagueoflegends/images/thumb/9/93/SejuaniSquare.png/20px-SejuaniSquare.png" width="20" height="20" data-image-name="SejuaniSquare.png" data-image-key="SejuaniSquare.png" data-src="http://img4.wikia.nocookie.net/__cb20130430130347/leagueoflegends/images/thumb/9/93/SejuaniSquare.png/20px-SejuaniSquare.png" class="lzyPlcHld lzyTrns lzyLoaded" onload="if(typeof ImgLzy==='object'){ImgLzy.load(this)}"><noscript>&lt;img src="http://img4.wikia.nocookie.net/__cb20130430130347/leagueoflegends/images/thumb/9/93/SejuaniSquare.png/20px-SejuaniSquare.png" width="20" height="20" data-image-name="SejuaniSquare.png" data-image-key="SejuaniSquare.png" /&gt;</noscript></a>&nbsp;<span><a href="/wiki/Sejuani" title="Sejuani">Sejuani</a></span></span>
</dt></dl>
<ul><li> <span style="white-space:nowrap;"><a href="/wiki/Sejuani#Arctic_Assault" title="Arctic Assault"><img src="http://img3.wikia.nocookie.net/__cb20130929123228/leagueoflegends/images/thumb/8/86/Arctic_Assault.png/20px-Arctic_Assault.png" width="20" height="20" data-image-name="Arctic Assault.png" data-image-key="Arctic_Assault.png" data-src="http://img3.wikia.nocookie.net/__cb20130929123228/leagueoflegends/images/thumb/8/86/Arctic_Assault.png/20px-Arctic_Assault.png" class="lzyPlcHld lzyTrns lzyLoaded" onload="if(typeof ImgLzy==='object'){ImgLzy.load(this)}"><noscript>&lt;img src="http://img3.wikia.nocookie.net/__cb20130929123228/leagueoflegends/images/thumb/8/86/Arctic_Assault.png/20px-Arctic_Assault.png" width="20" height="20" data-image-name="Arctic Assault.png" data-image-key="Arctic_Assault.png" /&gt;</noscript></a>&nbsp;<a href="/wiki/Sejuani#Arctic_Assault" title="Sejuani"><span title="Sejuani's Arctic Assault">Arctic Assault</span></a></span>
<ul><li> Fixed a bug where Arctic Assault was failing to knocked up champions above a certain size.
</li></ul>
</li></ul>
<dl><dt><span class="character_icon" style="white-space: nowrap"><a href="/wiki/Soraka" title="Soraka"><img src="http://img2.wikia.nocookie.net/__cb20140124030744/leagueoflegends/images/thumb/8/8d/SorakaSquare.png/20px-SorakaSquare.png" width="20" height="20" data-image-name="SorakaSquare.png" data-image-key="SorakaSquare.png" data-src="http://img2.wikia.nocookie.net/__cb20140124030744/leagueoflegends/images/thumb/8/8d/SorakaSquare.png/20px-SorakaSquare.png" class="lzyPlcHld lzyTrns lzyLoaded" onload="if(typeof ImgLzy==='object'){ImgLzy.load(this)}"><noscript>&lt;img src="http://img2.wikia.nocookie.net/__cb20140124030744/leagueoflegends/images/thumb/8/8d/SorakaSquare.png/20px-SorakaSquare.png" width="20" height="20" data-image-name="SorakaSquare.png" data-image-key="SorakaSquare.png" /&gt;</noscript></a>&nbsp;<span><a href="/wiki/Soraka" title="Soraka">Soraka</a></span></span>
</dt></dl>
<ul><li> <span style="white-space:nowrap;"><a href="/wiki/Soraka#Starcall" title="Starcall"><img src="http://img4.wikia.nocookie.net/__cb20140210184441/leagueoflegends/images/thumb/c/cd/Starcall.png/20px-Starcall.png" width="20" height="20" data-image-name="Starcall.png" data-image-key="Starcall.png" data-src="http://img4.wikia.nocookie.net/__cb20140210184441/leagueoflegends/images/thumb/c/cd/Starcall.png/20px-Starcall.png" class="lzyPlcHld lzyTrns lzyLoaded" onload="if(typeof ImgLzy==='object'){ImgLzy.load(this)}"><noscript>&lt;img src="http://img4.wikia.nocookie.net/__cb20140210184441/leagueoflegends/images/thumb/c/cd/Starcall.png/20px-Starcall.png" width="20" height="20" data-image-name="Starcall.png" data-image-key="Starcall.png" /&gt;</noscript></a>&nbsp;<a href="/wiki/Soraka#Starcall" title="Soraka"><span title="Soraka's Starcall">Starcall</span></a></span>
<ul><li> Damage lowered to 40 / 65 / 90 / 115 / 140 from 60 / 95 / 130 / 165 / 200.
</li><li> Astral Blessing's on-hit CDR increased to 5 / 8 / 11 / 14 / 17&nbsp;% from 5 / 6.25 / 7.5 / 8.75 / 10&nbsp;%.
</li></ul>
</li><li> <span style="white-space:nowrap;"><a href="/wiki/Soraka#Infuse" title="Infuse"><img src="http://img3.wikia.nocookie.net/__cb20140210184312/leagueoflegends/images/thumb/b/b1/Infuse.png/20px-Infuse.png" width="20" height="20" data-image-name="Infuse.png" data-image-key="Infuse.png" data-src="http://img3.wikia.nocookie.net/__cb20140210184312/leagueoflegends/images/thumb/b/b1/Infuse.png/20px-Infuse.png" class="lzyPlcHld lzyTrns lzyLoaded" onload="if(typeof ImgLzy==='object'){ImgLzy.load(this)}"><noscript>&lt;img src="http://img3.wikia.nocookie.net/__cb20140210184312/leagueoflegends/images/thumb/b/b1/Infuse.png/20px-Infuse.png" width="20" height="20" data-image-name="Infuse.png" data-image-key="Infuse.png" /&gt;</noscript></a>&nbsp;<a href="/wiki/Soraka#Infuse" title="Soraka"><span title="Soraka's Infuse">Infuse</span></a></span>
<ul><li> Enemy cast now costs 50 mana.
</li></ul>
</li></ul>
<dl><dt><span class="character_icon" style="white-space: nowrap"><a href="/wiki/Udyr" title="Udyr"><img src="http://img3.wikia.nocookie.net/__cb20091218195656/leagueoflegends/images/thumb/d/d1/UdyrSquare.png/20px-UdyrSquare.png" width="20" height="20" data-image-name="UdyrSquare.png" data-image-key="UdyrSquare.png" data-src="http://img3.wikia.nocookie.net/__cb20091218195656/leagueoflegends/images/thumb/d/d1/UdyrSquare.png/20px-UdyrSquare.png" class="lzyPlcHld lzyTrns lzyLoaded" onload="if(typeof ImgLzy==='object'){ImgLzy.load(this)}"><noscript>&lt;img src="http://img3.wikia.nocookie.net/__cb20091218195656/leagueoflegends/images/thumb/d/d1/UdyrSquare.png/20px-UdyrSquare.png" width="20" height="20" data-image-name="UdyrSquare.png" data-image-key="UdyrSquare.png" /&gt;</noscript></a>&nbsp;<span><a href="/wiki/Udyr" title="Udyr">Udyr</a></span></span>
</dt></dl>
<ul><li><span style="white-space:nowrap;"><a href="/wiki/Udyr#Bear_Stance" title="Bear Stance"><img src="http://img3.wikia.nocookie.net/__cb20130929123406/leagueoflegends/images/thumb/f/f0/Bear_Stance.png/20px-Bear_Stance.png" width="20" height="20" data-image-name="Bear Stance.png" data-image-key="Bear_Stance.png" data-src="http://img3.wikia.nocookie.net/__cb20130929123406/leagueoflegends/images/thumb/f/f0/Bear_Stance.png/20px-Bear_Stance.png" class="lzyPlcHld lzyTrns lzyLoaded" onload="if(typeof ImgLzy==='object'){ImgLzy.load(this)}"><noscript>&lt;img src="http://img3.wikia.nocookie.net/__cb20130929123406/leagueoflegends/images/thumb/f/f0/Bear_Stance.png/20px-Bear_Stance.png" width="20" height="20" data-image-name="Bear Stance.png" data-image-key="Bear_Stance.png" /&gt;</noscript></a>&nbsp;<a href="/wiki/Udyr#Bear_Stance" title="Udyr"><span title="Udyr's Bear Stance">Bear Stance</span></a></span>
<ul><li>Targets temporarily immune to Bear Stance now utilize the ring-indicator, as with Yasuo and Braum.
</li></ul>
</li></ul>